### ISSUE TITLE
Mauvaise qualité de la toile 

### ISSUE THREAD

**Issue by Lyndabenrahou** [LaitEau92/New-Age#4]
**Describe the bug**
Chute provoquée par la mauvaise qualité de la toile.

**To Reproduce**
1. Utilisation de la toile pour un déplacement
2. Toile déposée sur l'endroit souhaité
3. Saut à l'aide de la toile
4. Casse de la toile au moment du saut

**Expected behavior**
La toile devrait être solide.
**Screenshots**
Pas de screen possible

**Additional context**
Gravement blessé suite à la chute

**Comment by imRDA** [comment]
Problème résolu
