### ISSUE TITLE
Incapacité à retourner dans le présent

### ISSUE THREAD

**Issue by Lyndabenrahou** [LaitEau92/New-Age#5]
**Describe the bug**
Rencontre un problème avec la manipulation du temps.

**To Reproduce**

1.Être dans le présent
2. Aller dans le passé
3. Retourner dans le présent

**Expected behavior**

Pouvoir retourner dans le présent sans problème. 

**Screenshots**

Pas de screen possible.

**Additional context**

Se retrouve bloqué dans le passé

**Comment by LaitEau92** [comment]
Probleme résolu
